name: Run Selenium Tests
on:
  push:
    branches:
      - main # Change this to your default branch if different
  pull_request:
    branches:
      - main # Change this to your default branch if different

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Maven
      run: |
        sudo apt-get install maven -y
      shell: bash

    - name: Build and run Selenium tests
      run: |
        javac src/main/java/org/example/Main.java
        java -cp src/main/java org.example.Main
      working-directory: ${{ github.workspace }}
