name: Run Selenium Tests
on:
  push:
    branches:
      - main # Change this to your default branch if different
  pull_request:
    branches:
      - main # Change this to your default branch if different

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Chrome
      run: |
       CHROME_VERSION="118.0.5993.88"
       wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
       echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
       sudo apt-get update
       sudo apt-get install google-chrome-stable=$CHROME_VERSION -y
      shell: bash

    - name: Set up ChromeDriver
      run: |
       CHROMEDRIVER_VERSION="94.0.4606.61"  # Use the appropriate version matching your Chrome version
       wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
       unzip chromedriver_linux64.zip
       chmod +x chromedriver
       sudo mv chromedriver /usr/local/bin/
      shell: bash

    - name: Set up Maven
      run: |
        sudo apt-get install maven -y
      shell: bash

    - name: Build and run Selenium tests
      run: |
        mvn test 
      env:
        CHROME_BIN: /usr/bin/google-chrome
        CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
    # - name: Set up Maven
    #   run: |
    #     sudo apt-get install maven -y
    #   shell: bash

    # - name: Build and run Selenium tests
    #   run: |
    #     mvn test 

    #     # mvn clean test
    #     # javac src/main/java/org/example/Main.java
    #     # java -cp src/main/java org.example.Main

    #   working-directory: ${{ github.workspace }}
